import { name1, name2, num1, add } from "./data.js";
import { name, age } from "./data.js";
import { first, second } from "./data.js";
import { userName } from "./data.js";
console.log(add(1, 2));
console.log(name);
console.log(age);
console.log(first);
console.log(second);
console.log(userName);
